import { Poppins } from 'next/font/google';  // Fix the import statement for Poppins
import './globals.css';

// const inter = Inter({ subsets: ['latin'] });
const poppins = Poppins({ subsets: ['latin'],weight:"700",display:'auto' });  // Initialize Poppins font

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="valentine">
      <body className={` ${poppins.className}`}>{children}</body>
    </html>
  );
}
